# Generated by Django 5.1.4 on 2025-05-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
